/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicionesRouteImport } from './routes/mediciones'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EclipseRouteImport } from './routes/eclipse'
import { Route as DispositivoRouteImport } from './routes/dispositivo'
import { Route as AntecedentesRouteImport } from './routes/antecedentes'
import { Route as IndexRouteImport } from './routes/index'

const MedicionesRoute = MedicionesRouteImport.update({
  id: '/mediciones',
  path: '/mediciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EclipseRoute = EclipseRouteImport.update({
  id: '/eclipse',
  path: '/eclipse',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivoRoute = DispositivoRouteImport.update({
  id: '/dispositivo',
  path: '/dispositivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AntecedentesRoute = AntecedentesRouteImport.update({
  id: '/antecedentes',
  path: '/antecedentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/dispositivo': typeof DispositivoRoute
  '/eclipse': typeof EclipseRoute
  '/experiencia': typeof ExperienciaRoute
  '/mediciones': typeof MedicionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/dispositivo': typeof DispositivoRoute
  '/eclipse': typeof EclipseRoute
  '/experiencia': typeof ExperienciaRoute
  '/mediciones': typeof MedicionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/dispositivo': typeof DispositivoRoute
  '/eclipse': typeof EclipseRoute
  '/experiencia': typeof ExperienciaRoute
  '/mediciones': typeof MedicionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antecedentes'
    | '/dispositivo'
    | '/eclipse'
    | '/experiencia'
    | '/mediciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antecedentes'
    | '/dispositivo'
    | '/eclipse'
    | '/experiencia'
    | '/mediciones'
  id:
    | '__root__'
    | '/'
    | '/antecedentes'
    | '/dispositivo'
    | '/eclipse'
    | '/experiencia'
    | '/mediciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntecedentesRoute: typeof AntecedentesRoute
  DispositivoRoute: typeof DispositivoRoute
  EclipseRoute: typeof EclipseRoute
  ExperienciaRoute: typeof ExperienciaRoute
  MedicionesRoute: typeof MedicionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mediciones': {
      id: '/mediciones'
      path: '/mediciones'
      fullPath: '/mediciones'
      preLoaderRoute: typeof MedicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eclipse': {
      id: '/eclipse'
      path: '/eclipse'
      fullPath: '/eclipse'
      preLoaderRoute: typeof EclipseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivo': {
      id: '/dispositivo'
      path: '/dispositivo'
      fullPath: '/dispositivo'
      preLoaderRoute: typeof DispositivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antecedentes': {
      id: '/antecedentes'
      path: '/antecedentes'
      fullPath: '/antecedentes'
      preLoaderRoute: typeof AntecedentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntecedentesRoute: AntecedentesRoute,
  DispositivoRoute: DispositivoRoute,
  EclipseRoute: EclipseRoute,
  ExperienciaRoute: ExperienciaRoute,
  MedicionesRoute: MedicionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
